name: Update Date and Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update date in file
        run: |
          DATE=`date -u +"%Y-%m-%d %H:%M:%S UTC"`
          echo "export const lastUpdated = '$DATE'" > src/constants/lastUpdated.ts
          echo "Formatted date that will be posted: $(date -u +"%B %d, %Y %H:%M:%S UTC")"
          git config --global user.name 'Joshua Santos'
          git config --global user.email 'JoshCSan@gmail.com'
          git add src/constants/lastUpdated.ts

          # Check if there are any changes to commit
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
          else
            git commit -m 'Update last updated date'
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-cloudflare:
    needs: update-date
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      - name: Build
        run: pnpm install && pnpm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'portfolio-2024' # e.g. 'my-project'
          directory: 'dist' # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Revert commit if build fails
        if: failure()
        run: |
          git config --global user.email "JoshCSan@gmail.com"
          git config --global user.name "Joshua Santos"
          git revert HEAD --no-edit
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
