name: Update Date and Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update date in file
        run: |
          echo "const lastUpdated = '`date -u +"%Y-%m-%d %H:%M:%S UTC"`'" > src/constants/lastUpdated.js
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add src/constants/lastUpdated.js
          git commit -m 'Update last updated date'
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
          else
            git push origin HEAD:${{ github.ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-cloudflare:
    needs: update-date
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'portfolio-2024' # e.g. 'my-project'
          directory: dist # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}